---
# tasks file for httpd
- name: install software
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ httpd_packages[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(httpd_packages[ansible_distribution]
      | default(httpd_packages['default'] )) }}"

- name: allowing httpd to connect
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  when:
    - ansible_virtualization_type != "docker"

- name: configure software
  template:
    src: templates/application.conf.j2
    dest: "{{ httpd_directory[ansible_distribution] }}/{{ item.name }}.conf"
  with_items:
    - "{{ httpd_applications }}"
  notify:
    - restart software

- name: start and enable software
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ httpd_services[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(httpd_services[ansible_distribution]
      | default(httpd_services['default'] )) }}"
  when:
    - ansible_virtualization_type != "docker"
