---
# tasks file for httpd
- name: install software
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ httpd_configuration[ansible_distribution]['packages'] }}"

- name: install requirements
  pip:
    name: pyopenssl

- name: allowing httpd to connect
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  when:
    - ansible_selinux.status is defined
    - ansible_selinux.status == "enabled"

- name: create ssl directory
  file:
    path: "{{ httpd_configuration[ansible_distribution]['config_directory'] }}/ssl"
    state: directory

- name: create ssl key
  openssl_privatekey:
    path: "{{ httpd_configuration[ansible_distribution]['config_directory'] }}/ssl/{{ httpd_ssl_servername }}.key"
  register: key

- name: create ssl csr
  openssl_csr:
    path: "{{ httpd_configuration[ansible_distribution]['config_directory'] }}/ssl/{{ httpd_ssl_servername }}.csr"
    privatekey_path: "{{ key.filename }}"
    common_name: "{{ ansible_fqdn }}"
  register: csr

- name: create ssl certificates
  openssl_certificate:
    path: "{{ httpd_configuration[ansible_distribution]['config_directory'] }}/ssl/{{ httpd_ssl_servername }}.crt"
    privatekey_path: "{{ csr.privatekey }}"
    csr_path: "{{ csr.filename }}"
    provider: selfsigned

- name: configure ssl
  template:
    src: templates/ssl.conf.j2
    dest: "{{ httpd_configuration[ansible_distribution]['config_directory'] }}/ssl.conf"
    validate: '/usr/sbin/httpd -t -f %s'
  notify:
    - restart httpd

- name: configure application
  template:
    src: templates/application.conf.j2
    dest: "{{ httpd_configuration[ansible_distribution]['config_directory'] }}/{{ item.name }}.conf"
    validate: '/usr/sbin/httpd -t -f %s'
  with_items:
    - "{{ httpd_applications }}"
  notify:
    - restart httpd
  when:
    - httpd_applications is defined

- name: configure redirect from http to https
  template:
    src: templates/default_vhost.conf.j2
    dest: "{{ httpd_configuration[ansible_distribution]['config_directory'] }}/default_vhost.conf"
    validate: '/usr/sbin/httpd -t -f %s'
  notify:
    - restart httpd

- name: start and enable software
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ httpd_configuration[ansible_distribution]['service'] }}"
  when:
    - ansible_virtualization_type != "docker"
