---
# tasks file for httpd
- name: install apache httpd
  package:
    name: "{{ httpd_packages[ansible_distribution]
          | default(httpd_packages['default']) }}"
    state: "{{ httpd_package_state }}"

- name: install requirements
  pip:
    name: "{{ httpd_requirements }}"
    state: present

- name: modify selinux settings
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  when:
    - ansible_selinux.status is defined
    - ansible_selinux.status == "enabled"
  with_items:
    - "{{ httpd_sebooleans }}"

- name: create ssl directory
  file:
    path: "{{ httpd_config_directory[ansible_distribution]
          | default(httpd_config_directory['default']) }}/ssl"
    state: directory

- name: create ssl key
  openssl_privatekey:
    path: "{{ httpd_config_directory[ansible_distribution]
          | default(httpd_config_directory['default']) }}/ssl/{{ httpd_ssl_servername }}.key"
  register: key

- name: create ssl csr
  openssl_csr:
    path: "{{ httpd_config_directory[ansible_distribution]
          | default(httpd_config_directory['default']) }}/ssl/{{ httpd_ssl_servername }}.csr"
    privatekey_path: "{{ key.filename }}"
    common_name: "{{ httpd_ssl_servername }}"
  register: csr

- name: create ssl certificates
  openssl_certificate:
    path: "{{ httpd_config_directory[ansible_distribution]
          | default(httpd_config_directory['default']) }}/ssl/{{ httpd_ssl_servername }}.crt"
    privatekey_path: "{{ csr.privatekey }}"
    csr_path: "{{ csr.filename }}"
    provider: selfsigned

- name: configure ssl
  template:
    src: ssl.conf.j2
    dest: "{{ httpd_config_directory[ansible_distribution]
          | default(httpd_config_directory['default']) }}/ssl.conf"
  notify:
    - restart httpd

- name: configure locations
  template:
    src: location.conf.j2
    dest: "{{ httpd_config_directory[ansible_distribution]
          | default(httpd_config_directory['default']) }}/{{ item.name }}.conf"
  with_items:
    - "{{ httpd_locations }}"
  notify:
    - restart httpd
  when:
    - httpd_locations is defined
  loop_control:
    label: "{{ item.name }}"

- name: configure vhosts
  template:
    src: vhost.conf.j2
    dest: "{{ httpd_config_directory[ansible_distribution]
          | default(httpd_config_directory['default']) }}/{{ item.name }}.conf"
  with_items:
    - "{{ httpd_vhosts }}"
  notify:
    - restart httpd
  when:
    - httpd_vhosts is defined
  loop_control:
    label: "{{ item.name }}"

- name: configure redirect from http to https
  template:
    src: default_vhost.conf.j2
    dest: "{{ httpd_config_directory[ansible_distribution]
          | default(httpd_config_directory['default']) }}/default_vhost.conf"
  notify:
    - restart httpd

- name: start and enable software
  service:
    name: "{{ httpd_service[ansible_distribution]
          | default(httpd_service['default']) }}"
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker"
