---
# tasks file for httpd
- name: install software
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ httpd_packages[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(httpd_packages[ansible_distribution]
      | default(httpd_packages['default'] )) }}"

- name: start and enable software
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ httpd_services[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(httpd_services[ansible_distribution]
      | default(httpd_services['default'] )) }}"
  when:
    - ansible_virtualization_type != "docker"
