---
- name: Converge
  hosts: all
  gather_facts: no
  become: yes

  vars:
    httpd_locations:
      - name: mylocation2
        location: /mylocation1
        backend_url: http://localhost:8080/myapplication
    httpd_vhosts:
      - name: myvhost1
        servername: www1.example.com
        documentroot: /var/www/html/www1.example.com
      - name: myvhost2
        servername: www2.example.com
        documentroot: /var/www/html/www2.example.com
        backend_url: http://www.example.com/
      - name: myvhost3
        servername: www3.example.com
        documentroot: /var/www/html/www3.example.com
        backend_url: http://www.example.com/
        remote: http://localhost:3128/

  roles:
    - robertdebock.bootstrap
    - robertdebock.python_pip
    - ansible-role-httpd
