---
- name: Converge
  hosts: all
  gather_facts: no
  become: yes

  vars:
    httpd_applications:
      - name: myapplication
        location: /myapplication
        backend_url: http://localhost:8080/myapplication
      - name: myotherapp
        location: myotherapp
        backend_url: http://localhost:8080/myotherapp
      - name: fedoraproxy
        location: fedoraproxy
        backend_url: http://dl.fedoraproject.org/pub/fedora/linux/
        remote: http://localhost:3128/

  roles:
    - robertdebock.bootstrap
    - robertdebock.python_pip
    - ansible-role-httpd
