---
# handlers file for httpd
- name: restart httpd
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - "{{ httpd_configuration[ansible_distribution]['service'] }}"
  when:
    - ansible_virtualization_type != "docker"
