---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: default
    image: "${distribution:-robertdebock/docker-fedora-systemd:latest}"
    command: "${command:-sleep infinity}"
    pre_build_image: yes
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: playbook.yml
scenario:
  name: default
