---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: httpd-opensuse-tumbleweed
    image: opensuse:tumbleweed
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        httpd_ignore_docker: no
  lint:
    name: ansible-lint
  config_options:
    defaults:
      callback_plugins: /usr/lib/python2.7/site-packages/ara/plugins/callbacks
scenario:
  name: opensuse-tumbleweed
verifier:
  name: goss
  lint:
    name: yamllint
